---
build_from:
  aarch64: ghcr.io/hassio-addons/base-python/aarch64:9.0.1
  amd64: ghcr.io/hassio-addons/base-python/amd64:9.0.1
  armhf: ghcr.io/hassio-addons/base-python/armhf:9.0.1
  armv7: ghcr.io/hassio-addons/base-python/armv7:9.0.1
  i386: ghcr.io/hassio-addons/base-python/i386:9.0.1
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
args:
  DEHYDRATED_VERSION: v0.7.0
  LEXICON_VERSION: 3.11.4
  PIP_VERSION: 22.2.2
